"use client";
import Link from "next/link";
import { PlaceFilter } from "./PlaceFilter";
import { useRouter } from "next/navigation";
import { useCallback,useEffect,useRef,useState,type FormEvent } from "react";
import { Car,ArrowRight,Plus,Users,MapPin } from "lucide-react";
import { TRIP_STATUS,MEMBER_STATUS,GENDER_PREFERENCE,type GenderPreference,type CarpoolTrip,type CarpoolPlace,type CarpoolDetail,type CarpoolMessage } from "@/lib/carpool";
import { useMessagePolling,MessageFailure,LoadingMessages,RequestError,updateUnread } from "@/components/messages/shared";

async function api<T>(query="",body?:unknown,signal?:AbortSignal):Promise<T>{const r=await fetch(`/api/carpool${query}`,{method:body?"POST":"GET",cache:"no-store",signal,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new RequestError(data.error||"请求失败",r.status);return data;}
const dt=(date:string)=>new Date(date).toLocaleString("zh-CN",{timeZone:"Asia/Shanghai",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});
const inputTime=(value:FormDataEntryValue|null)=>new Date(`${value}:00+08:00`).toISOString();
const button="min-h-11 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white disabled:opacity-40";
function Frame({children,title}:{children:React.ReactNode;title:string}){return <div className="mx-auto max-w-3xl px-4 py-5"><div className="mb-5 flex items-center justify-between gap-2"><Link href="/carpool" className="flex items-center gap-2 text-blue-600"><Car className="size-6" /><h1 className="text-xl font-black">{title}</h1></Link><Link href="/carpool/mine" className="inline-flex min-h-11 items-center text-sm font-bold text-slate-600">我的拼车</Link></div>{children}</div>;}
function TripCard({trip}:{trip:CarpoolTrip}){return <Link href={`/carpool/${trip.id}`} className="card block p-5"><div className="flex flex-wrap justify-between gap-2"><strong className="text-blue-700">{dt(trip.departure_start)}</strong><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{TRIP_STATUS[trip.display_status]}</span></div><p className="mt-1 text-xs text-slate-400">最晚出发 {dt(trip.departure_end)}</p><h2 className="mt-4 flex items-center gap-2 text-lg font-black"><span>{trip.origin}</span><ArrowRight className="size-4 shrink-0 text-blue-400" /><span>{trip.destination}</span></h2><p className="mt-3 flex items-center gap-2 text-sm text-slate-600"><Users className="size-4" />已有 {trip.occupied} 人 · 还缺 {Math.max(0,trip.capacity-trip.occupied)} 人</p><p className="mt-2 text-xs text-slate-500">按实际打车费用按人数分摊</p><p className="mt-2 text-xs font-bold text-blue-700">同行要求：{GENDER_PREFERENCE[trip.gender_preference]}</p><div className="mt-4 flex justify-between gap-3 border-t border-slate-100 pt-3 text-xs text-slate-400"><span>{trip.host_name} · 发起时已认证</span><span>{trip.my_status?MEMBER_STATUS[trip.my_status]:"查看详情 →"}</span></div></Link>;}

export function CarpoolHall({mine=false}:{mine?:boolean}){
 const [filters,setFilters]=useState("");const [page,setPage]=useState(0);
 const loader=useCallback(async(signal:AbortSignal)=>({...await api<{trips:CarpoolTrip[];hasMore:boolean}>(`?mine=${mine}&page=${page}${filters}`,undefined,signal),key:`${page}${filters}`}),[mine,page,filters]);
 const {data,error,busy,refresh}=useMessagePolling(loader,true,30000);
 const placesLoader=useCallback((signal:AbortSignal)=>api<{places:CarpoolPlace[]}>("?view=places",undefined,signal),[]);
 const places=useMessagePolling(placesLoader,true,60000);
 const current=data?.key===`${page}${filters}`?data:undefined;
 function filter(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),q=new URLSearchParams();for(const field of ["originText","destinationText","gender"]){const value=String(f.get(field)||"").trim();if(value)q.set(field,value);}const earliest=String(f.get("earliest")||"");if(earliest){const day=earliest.slice(0,10);q.set("from",new Date(`${earliest}:00+08:00`).toISOString());q.set("to",new Date(new Date(`${day}T00:00:00+08:00`).getTime()+86400000).toISOString());}setPage(0);setFilters(`&${q}`);}
 return <Frame title={mine?"我的拼车":"校园拼车"}><section className="mb-5 rounded-3xl bg-blue-600 p-5 text-white"><h2 className="text-2xl font-black">找同路，一起出发</h2><p className="mt-2 text-sm leading-6 text-blue-100">同学组队后自行通过正规出行平台叫车，费用按实际车费分摊。</p><Link href="/carpool/new" className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-blue-700"><Plus className="size-4" />发起拼车</Link></section>
 <form onSubmit={filter} className="card mb-5 grid grid-cols-2 gap-3 p-4"><PlaceFilter name="originText" label="出发地" presets={["东区校门口","中区校门口","西区校门口"]} places={places.data?.places.map(p=>p.name)||[]} /><PlaceFilter name="destinationText" label="目的地" presets={["莆田站","涵江站"]} places={places.data?.places.map(p=>p.name)||[]} /><label className="label col-span-2 sm:col-span-1">不早于（北京时间）<input type="datetime-local" name="earliest" className="field" /></label><label className="label col-span-2">同行要求<select name="gender" className="field"><option value="">全部要求</option>{Object.entries(GENDER_PREFERENCE).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><button className={`${button} col-span-2`}>筛选行程</button></form>
 {places.error&&<MessageFailure error={places.error} retry={places.refresh}/>}{error&&<MessageFailure error={error} retry={refresh}/>}{!current&&!error&&<LoadingMessages label="正在加载拼车信息…"/>}
 <section className="grid gap-4">{current?.trips.map(t=><TripCard key={t.id} trip={t}/>)}{current&&!current.trips.length&&<div className="card p-10 text-center text-sm text-slate-500">{mine?"你还没有符合条件的行程":"暂无符合条件的同行，可以调整筛选或发起拼车。"}</div>}</section><div className="mt-4 flex items-center justify-between text-sm"><button className="min-h-11 px-3 text-blue-600 disabled:opacity-30" disabled={!page||busy} onClick={()=>setPage(p=>p-1)}>上一页</button><span>第 {page+1} 页</span><button className="min-h-11 px-3 text-blue-600 disabled:opacity-30" disabled={!current?.hasMore||busy} onClick={()=>setPage(p=>p+1)}>下一页</button></div></Frame>;
}
export function CarpoolCreate(){
 const [preference,setPreference]=useState<GenderPreference>("ANY");const [confirmed,setConfirmed]=useState(false);
 const router=useRouter();const [error,setError]=useState<Error>();const [busy,setBusy]=useState(false);const key=useRef<{value:string;id:string}|null>(null);
 const loader=useCallback((signal:AbortSignal)=>api<{places:CarpoolPlace[]}>("?view=places",undefined,signal),[]);const places=useMessagePolling(loader,true,60000);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError(undefined);try{const f=new FormData(e.currentTarget);const payload={action:"create",genderPreference:preference,genderConfirmed:preference!=="ANY"&&confirmed,originName:String(f.get("originName")||"").trim(),destinationName:String(f.get("destinationName")||"").trim(),start:inputTime(f.get("start")),end:inputTime(f.get("end")),partySize:Number(f.get("partySize")),capacity:Number(f.get("capacity")),meeting:f.get("meeting"),luggage:f.get("luggage")};const value=JSON.stringify(payload);if(key.current?.value!==value)key.current={value,id:crypto.randomUUID()};const result=await api<{id:string}>("",{...payload,clientId:key.current.id});router.push(`/carpool/${result.id}`);}catch(e){setError(e as Error);}finally{setBusy(false);}}
 return <Frame title="发起拼车"><p className="mb-4 text-sm leading-6 text-slate-500">仅已认证同校用户可发起。已有同行也占人数，计划人数不代表已有车辆或座位。</p>{places.error&&<MessageFailure error={places.error} retry={places.refresh}/>}<form onSubmit={submit} className="card grid gap-4 p-5"><PlaceFilter required name="originName" label="出发地" presets={["东区校门口","中区校门口","西区校门口"]} places={places.data?.places.filter(p=>p.active).map(p=>p.name)||[]} /><PlaceFilter required name="destinationName" label="目的地" presets={["莆田站","涵江站"]} places={places.data?.places.filter(p=>p.active).map(p=>p.name)||[]} /><div className="grid gap-4 sm:grid-cols-2"><label className="label">最早出发（北京时间）<input required name="start" type="datetime-local" className="field" /></label><label className="label">最晚出发（最长间隔6小时）<input required name="end" type="datetime-local" className="field" /></label><label className="label">已有同行人数（含自己）<input name="partySize" type="number" required min={1} max={5} defaultValue={1} className="field" /></label><label className="label">计划总人数（2～6人）<input name="capacity" type="number" required min={2} max={6} defaultValue={3} className="field" /></label></div><label className="label">同行性别要求<select className="field" value={preference} onChange={e=>{setPreference(e.target.value as GenderPreference);setConfirmed(false);}}>{Object.entries(GENDER_PREFERENCE).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>{preference!=="ANY"&&<label className="flex min-h-11 items-start gap-2 rounded-xl bg-blue-50 p-3 text-sm leading-6 text-blue-800"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1.5 size-4 shrink-0"/>我确认本人及已有同行均符合“{GENDER_PREFERENCE[preference]}”要求。此为本人声明，平台未核验性别。</label>}<label className="label">行李说明<input name="luggage" maxLength={200} placeholder="例如：1件大行李，请勿填写联系方式" className="field" /></label><label className="label">集合说明（仅确认成员可见）<textarea name="meeting" required minLength={2} maxLength={500} rows={3} className="field" /></label><p className="rounded-xl bg-blue-50 p-3 text-xs leading-6 text-blue-700">费用按实际打车费按人数分摊，平台不收取车费、不提供车辆。同行者请自行确认适合人数及行李的车型。</p>{error&&<MessageFailure error={error} retry={()=>setError(undefined)}/>}<button disabled={busy} className={button}>{busy?"发布中…":"发布行程"}</button></form></Frame>;
}
export function CarpoolTripDetail({id}:{id:string}){
 const [confirmed,setConfirmed]=useState(false);
 const loader=useCallback((signal:AbortSignal)=>api<CarpoolDetail>(`?view=detail&id=${id}`,undefined,signal),[id]);const {data,error,refresh}=useMessagePolling(loader,true,15000);
 const denied=error instanceof RequestError&&[401,403,404].includes(error.status);
 const [failure,setFailure]=useState<Error>();const [busy,setBusy]=useState(false);const [size,setSize]=useState(1);const [meeting,setMeeting]=useState("");
 async function act(body:Record<string,unknown>){if(busy)return;setBusy(true);setFailure(undefined);try{await api("",{...body,id});refresh();updateUnread();}catch(e){setFailure(e as Error);refresh();}finally{setBusy(false);}}
 return <Frame title="拼车详情">{error&&<MessageFailure error={error} retry={refresh}/>} {!data&&!error&&<LoadingMessages label="正在加载拼车信息…"/>}{data&&!denied&&<><TripCard trip={data.trip}/><section className="card mt-4 space-y-3 p-5"><h2 className="font-bold">同行说明</h2><p className="text-sm text-slate-600">行李：{data.trip.luggage||"未填写"}</p><p className="whitespace-pre-wrap text-sm leading-7 text-slate-600">集合：{data.meeting||"确认加入后可查看详细集合说明"}</p><p className="text-xs leading-6 text-slate-500">费用以实际叫车账单为准，按同行人数分摊。请自行通过正规出行平台叫车。</p></section>
 {!data.verified&&<Link href="/profile" className="mt-4 block rounded-xl bg-blue-50 p-4 text-sm text-blue-700">完成校园认证后可申请加入 →</Link>}
 {!data.trip.my_status&&data.verified&&data.trip.display_status==="OPEN"&&<form className="card mt-4 grid gap-3 p-4" onSubmit={e=>{e.preventDefault();void act({action:"apply",partySize:size,genderConfirmed:confirmed});}}><label className="label">申请同行人数（含自己）<input className="field" type="number" min={1} max={data.trip.capacity-data.trip.occupied} value={size} onChange={e=>setSize(Number(e.target.value))}/></label>{data.trip.gender_preference!=="ANY"&&<label className="flex min-h-11 items-start gap-2 text-sm leading-6 text-slate-600"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1.5 size-4 shrink-0"/>我确认本人及本次申请的全部同行均符合“{GENDER_PREFERENCE[data.trip.gender_preference]}”要求（本人声明，非平台核验）。</label>}<button disabled={busy||(data.trip.gender_preference!=="ANY"&&!confirmed)} className={button}>申请加入，等待发起人确认</button></form>}
 {data.canChat&&<Link href={`/carpool/${id}/chat`} className="mt-4 flex min-h-12 items-center justify-center rounded-xl bg-blue-600 font-bold text-white">进入行程群聊</Link>}
 {data.members.length>0&&<section className="card mt-4 p-4"><h2 className="mb-3 font-bold">同行成员与申请</h2>{data.members.map(m=><div key={m.user_id} className="flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 py-3"><span className="text-sm">{m.name} · {m.party_size} 人 · {MEMBER_STATUS[m.status]}</span>{data.isOwner&&m.status==="PENDING"&&<div className="flex gap-2"><button disabled={busy||!["OPEN","FULL"].includes(data.trip.display_status)} className={button} onClick={()=>act({action:"respond",userId:m.user_id,accept:true})}>同意</button><button disabled={busy||!["OPEN","FULL"].includes(data.trip.display_status)} className="min-h-11 px-3 text-sm text-slate-500" onClick={()=>act({action:"respond",userId:m.user_id,accept:false})}>拒绝</button></div>}</div>)}</section>}
 {!data.isOwner&&["APPROVED","PENDING"].includes(data.trip.my_status||"")&&data.trip.status==="OPEN"&&<button disabled={busy} onClick={()=>{if(window.confirm("确认退出或撤回申请？退出后无法再加入本行程，也无法访问群聊。"))void act({action:"leave"});}} className="mt-4 min-h-11 w-full rounded-xl border border-slate-200 text-sm text-slate-600">退出 / 撤回申请</button>}
 {data.isOwner&&<section className="card mt-4 space-y-3 p-4"><h2 className="font-bold">管理行程</h2>{["OPEN","FULL"].includes(data.trip.display_status)&&<form onSubmit={e=>{e.preventDefault();void act({action:"meeting",meeting,version:data.trip.version});}} className="grid gap-3"><label className="label">更新集合说明<textarea className="field" rows={2} required minLength={2} maxLength={500} value={meeting} onChange={e=>setMeeting(e.target.value)} /></label><button disabled={busy} className={button}>通知成员并更新</button></form>}<div className="flex flex-wrap gap-2">{data.trip.status==="OPEN"&&<><button disabled={busy||!data.canDepart} onClick={()=>{if(window.confirm("确认所有同行者已集合并出发？"))void act({action:"state",state:"DEPARTED",version:data.trip.version});}} className={button}>确认出发</button><button disabled={busy} onClick={()=>{if(window.confirm("取消后会通知所有申请人及成员，确认取消？"))void act({action:"state",state:"CANCELLED",version:data.trip.version});}} className="min-h-11 rounded-xl border border-red-200 px-4 text-sm text-red-600">取消行程</button></>}{data.trip.status==="DEPARTED"&&<button disabled={busy} onClick={()=>{if(window.confirm("确认行程已经结束？"))void act({action:"state",state:"COMPLETED",version:data.trip.version});}} className={button}>确认结束</button>}</div></section>}
 {failure&&<MessageFailure error={failure} retry={()=>{setFailure(undefined);refresh();}}/>}<div className="mt-5 flex justify-between text-sm text-blue-700"><Link className="min-h-11 py-3" href={`/support/new?trip=${id}`}>联系客服</Link><Link className="min-h-11 py-3" href={`/support/new?trip=${id}`}>举报此行程</Link></div></>}</Frame>;
}

type GroupData={messages:CarpoolMessage[];hasMore:boolean;userId:string;readOnly:boolean};
function GroupReadMarker({id,through}:{id:string;through:string}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{
  if(!ref.current)return;
  let visible=false,pending=false,done=false;
  async function read(){if(!visible||pending||done||document.visibilityState!=="visible")return;pending=true;try{await api("",{action:"read",id,through});done=true;updateUnread();}catch{/* Retry only while the latest message is visible. */}finally{pending=false;}}
  const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;void read();});observer.observe(ref.current);
  const timer=setInterval(read,15000);document.addEventListener("visibilitychange",read);
  return()=>{observer.disconnect();clearInterval(timer);document.removeEventListener("visibilitychange",read);};
 },[id,through]);
 return <div ref={ref} className="h-1" aria-hidden="true"/>;
}
export function CarpoolGroupChat({id}:{id:string}){
 const cache=useRef<GroupData|null>(null);const [history,setHistory]=useState<CarpoolMessage[]>([]);const [more,setMore]=useState<boolean>();const [body,setBody]=useState("");const [busy,setBusy]=useState(false);const [failure,setFailure]=useState<Error>();const sendKey=useRef<{body:string;id:string}|null>(null);
 const loader=useCallback(async(signal:AbortSignal)=>{try{
  let result:GroupData;
  if(!cache.current?.messages.length)result=await api<GroupData>(`?view=chat&id=${id}`,undefined,signal);
  else{result={...cache.current,messages:[...cache.current.messages]};let more=true;while(more){const page=await api<GroupData>(`?view=chat&id=${id}&after=${result.messages.at(-1)!.id}`,undefined,signal);result.messages.push(...page.messages);result.readOnly=page.readOnly;more=page.hasMore;}}
  if(!signal.aborted)cache.current=result;return result;
 }catch(e){if(e instanceof RequestError&&[401,403,404].includes(e.status))cache.current=null;throw e;}},[id]);
 const {data,error,refresh}=useMessagePolling(loader,true,5000);
 const denied=error instanceof RequestError&&[401,403,404].includes(error.status);
 const rows=[...new Map([...history,...(data?.messages||[])].map(m=>[m.id,m])).values()].sort((a,b)=>BigInt(a.id)<BigInt(b.id)?-1:1);
 async function send(e:FormEvent){e.preventDefault();if(busy||!body.trim())return;setBusy(true);setFailure(undefined);if(sendKey.current?.body!==body)sendKey.current={body,id:crypto.randomUUID()};try{await api("",{action:"send",id,body,clientId:sendKey.current.id});setBody("");sendKey.current=null;refresh();updateUnread();}catch(e){setFailure(e as Error);refresh();}finally{setBusy(false);}}
 async function older(){if(!rows[0]||busy)return;setBusy(true);try{const page=await api<GroupData>(`?view=chat&id=${id}&before=${rows[0].id}`);setHistory(h=>[...page.messages,...h]);setMore(page.hasMore);}catch(e){setFailure(e as Error);refresh();}finally{setBusy(false);}}
 return <Frame title="行程群聊"><Link href={`/carpool/${id}`} className="mb-4 inline-flex min-h-11 items-center text-sm text-blue-600">← 返回行程详情</Link>{error&&<MessageFailure error={error} retry={refresh}/>} {!data&&!error&&<LoadingMessages label="正在加载拼车信息…"/>}{data&&!denied&&<><p className="mb-4 rounded-xl bg-blue-50 p-3 text-xs leading-6 text-blue-700">仅当前确认成员可访问，仅展示加入后的消息。退出后群聊权限关闭。</p><section aria-label="行程群聊记录" className="space-y-3">{(more??data.hasMore)&&<button disabled={busy} onClick={older} className="min-h-11 w-full text-sm text-blue-600">查看更早消息</button>}{!rows.length&&<p className="card p-8 text-center text-sm text-slate-500">暂无消息，和同行同学打个招呼吧。</p>}{rows.map(m=><div key={m.id} className={`rounded-2xl border p-4 ${m.sender_id===data.userId?"border-blue-100 bg-blue-50":"border-slate-200 bg-white"}`}><p className="text-xs text-slate-400">{m.sender_id===data.userId?"我":m.name} · {dt(m.created_at)}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7">{m.body}</p></div>)}</section>{rows.length>0&&<GroupReadMarker id={id} through={rows.at(-1)!.id}/>} {rows.length>0&&<button className="mt-3 min-h-11 text-xs text-blue-600" onClick={async()=>{try{await api("",{action:"read",id,through:rows.at(-1)!.id});updateUnread();}catch(e){setFailure(e as Error);}}}>已读至最新消息</button>}{data.readOnly?<p className="mt-4 text-sm text-slate-500">行程已结束、取消或过期，群聊只读。</p>:<form onSubmit={send} className="card mt-4 grid gap-3 p-4"><label className="label">群聊消息<textarea required maxLength={2000} rows={3} className="field" value={body} onChange={e=>setBody(e.target.value)} placeholder="与同行同学确认集合安排" /></label><button disabled={busy||!body.trim()} className={button}>发送消息</button></form>}</>}{failure&&<MessageFailure error={failure} retry={()=>{setFailure(undefined);refresh();}}/>}</Frame>;
}
export function CarpoolPlaceAdmin(){
 const loader=useCallback((signal:AbortSignal)=>api<{places:CarpoolPlace[]}>("?view=places",undefined,signal),[]);const {data,error,refresh}=useMessagePolling(loader,true,60000);const [failure,setFailure]=useState<Error>();const [busy,setBusy]=useState(false);
 async function save(body:unknown){setBusy(true);setFailure(undefined);try{await api("",body);refresh();}catch(e){setFailure(e as Error);}finally{setBusy(false);}}
 return <Frame title="拼车地点配置"><p className="mb-4 text-sm leading-6 text-slate-500">配置本校可用的真实出发地和目的地。停用地点不影响已有行程记录，不再允许新行程选用。</p>{error&&<MessageFailure error={error} retry={refresh}/>}<form className="card mb-4 flex gap-2 p-4" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;void save({action:"place",name:new FormData(form).get("name"),active:true});}}><input name="name" required minLength={2} maxLength={80} className="field min-w-0 flex-1" placeholder="真实地点名称" aria-label="地点名称"/><button disabled={busy} className={button}>添加</button></form>{data?.places.map(p=><div key={p.id} className="card mb-3 flex items-center justify-between gap-3 p-4"><span className="text-sm">{p.name} · {p.active?"已启用":"已停用"}</span><button disabled={busy} className="min-h-11 shrink-0 px-3 text-sm text-blue-600" onClick={()=>save({action:"place",id:p.id,name:p.name,active:!p.active})}>{p.active?"停用":"启用"}</button></div>)}{failure&&<MessageFailure error={failure} retry={()=>setFailure(undefined)}/>}<MapPin className="mx-auto mt-8 size-7 text-blue-200"/></Frame>;
}
